apiVersion: v1 
kind: Service 
metadata:
  name: netflix-app-service
spec:
  type: NodePort
  selector:
    app: netflix-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP