name: Netflix Clone CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  sonar_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: 
            -Dsonar.projectKey=${{ vars.PROJECT_NAME }}
            -Dsonar.organization=${{ vars.PROJECT_NAME }}
            -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
            
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          sonar-host-url: ${{ var.SONAR_HOST_URL }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          waitForQualityGate: 'true'

  
